CSVFILE_STORE_FOLDER_NAME = '..//stockPriceCSV'
CSVFILE_EXTENSION = '.csv'
DBConnectionINIFile = 'DBConnection.ini'

DROP_COLUMN_NAME_DATE = '日付'

TECHNICAL_INDEX_COLUMN_NAME_OPEN = '始値'
TECHNICAL_INDEX_COLUMN_NAME_CLOSE = '終値'
TECHNICAL_INDEX_COLUMN_NAME_LOW = '安値'
TECHNICAL_INDEX_COLUMN_NAME_HIGH = '高値'
TECHNICAL_INDEX_COLUMN_NAME_SHORT_EMA = '短期EMA'
TECHNICAL_INDEX_COLUMN_NAME_MIDDLE_EMA = '中期EMA'
TECHNICAL_INDEX_COLUMN_NAME_LONG_EMA = '長期EMA'
TECHNICAL_INDEX_COLUMN_NAME_MACD = 'MACD'
TECHNICAL_INDEX_COLUMN_NAME_SIGNAL = 'シグナル'
TECHNICAL_INDEX_COLUMN_NAME_PLUS_DI = '+DI'
TECHNICAL_INDEX_COLUMN_NAME_MINUS_DI = '-DI'
TECHNICAL_INDEX_COLUMN_NAME_ADX = 'ADX'

PREVIOUS_COLUMN_PREFIX = '前日'
DIFFERENCE_COLUMN_SUFFIX = '差'

DROP_COLUMN_NAME_LIST = [DROP_COLUMN_NAME_DATE]
TRAINING_TECHNICAL_INDEX_COLUMN_NAME_LIST = [TECHNICAL_INDEX_COLUMN_NAME_CLOSE,
                                             TECHNICAL_INDEX_COLUMN_NAME_SHORT_EMA, TECHNICAL_INDEX_COLUMN_NAME_MIDDLE_EMA, TECHNICAL_INDEX_COLUMN_NAME_LONG_EMA,
                                             TECHNICAL_INDEX_COLUMN_NAME_MACD, TECHNICAL_INDEX_COLUMN_NAME_SIGNAL,
                                             TECHNICAL_INDEX_COLUMN_NAME_PLUS_DI, TECHNICAL_INDEX_COLUMN_NAME_MINUS_DI, TECHNICAL_INDEX_COLUMN_NAME_ADX]


